# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "default" do |web|
    web.vm.box = "ubuntu/trusty64"
    web.vm.boot_timeout = 900
    # web.vm.hostname = "hostname"

    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end

    # web.vm.network :forwarded_port, guest:22, host:2001, id:"ssh"
    # web.vm.network :forwarded_port, guest:80, host:8080, id:"http"
    web.vm.network :private_network, ip: "192.168.50.11"
  end
end
