# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "centos66" do |web|
    web.vm.box = "chef/centos-6.6"
    web.vm.boot_timeout = 900
    # web.vm.hostname = "hostname"

    # web.vm.network :forwarded_port, guest:22, host:2001, id:"ssh"
    # web.vm.network :forwarded_port, guest:80, host:8080, id:"http"
    # web.vm.network :private_network, ip: "192.168.50.11"
  end
end
